### ISSUE TITLE
[Weekly] 2021-07–21

### ISSUE THREAD

**Issue by NikkelM** [hpi-swa-teaching/Liquid#127]
Last week: #119

**Comment by NikkelM** [comment]
- [ ] Discuss #128

**Comment by Skn0tt** [comment]
- [ ] evtl Retro
- [ ] Was muss noch getan werden? Ne große Liste wäre super
- [ ] Announcement: Liquid Hacking Hours

**Comment by Skn0tt** [comment]
Answer to "Should we exclude UI from our test coverage?": no. according to @frcroth, this is A. unusual and B. test coverage is not grade-relevant
