### ISSUE TITLE
Docs: Hacky Code

### ISSUE THREAD

**Issue by NikkelM** [hpi-swa-teaching/Liquid#142]

**Comment by Skn0tt** [comment]
ParticipantMenu: importPollWithId
PollDraftBuilder: buildMaxNumberOfChoicesLabelWith: 
changeClosePollButtonToVisualizeResultsButton
LiquidRunningPollView: closePoll
ParticipantMenu: buildAnswerPanelWith
AnswerPanel: choiceAt: anIndex put: aBoolean
AnswerPanel: getChildren
AnswerPanel: question

**Comment by Skn0tt** [comment]
@NikkelM will open a PR to fix all of these, so we don't need to document them
