### ISSUE TITLE
Collect & Ideate User Stories

### ISSUE THREAD

**Issue by Skn0tt** [hpi-swa-teaching/Liquid#2]
Please comment your user story ideas down below 👇

They'll be turned into individual User Story issues in our next Wed meeting.

**Comment by Skn0tt** [comment]
As a host, I want to have support for >200 users, so I can actually use it for end-of-term presentation.

**Comment by Skn0tt** [comment]
As a host, I want to know that there's no way for clients to cheat, so I can actually rely on the results.

This could be implemented using some kind of hash-based message authentication scheme.

**Comment by NikkelM** [comment]
As a host, I want to be able to choose between different types of answer modes, such as single-choice, multiple-choice, free-text and prioritisation, so I can make sure I get answers that fit my questions.

**Comment by NikkelM** [comment]
As a host, I want to be able to export results into a fitting format (e.g. CSV), so I can save them for later use.

**Comment by Shieka** [comment]
As a poll participant, I want to be able to undo my choices before I submit them, so I can reconsider or fix accidental clicks.

**Comment by NikkelM** [comment]
As a host, I want to be able to ask multiple questions in one poll, so I can ask more specific questions instead of one generalised one, as well as make the process easier for my participants.

**Comment by NikkelM** [comment]
As a host, I want to be able to choose whether or not participants can see the poll results, so I can create polls where the results are only meant for internal use.

**Comment by richardschiemenz** [comment]
As a host, I want to have a visualization of the results, so I can easily evaluate the answers.

**Comment by Skn0tt** [comment]
As a poll participant, I want to get a _clear_ idea of the poll's characteristics (number of votes allowed / who can see the results / ...), so I don't make mistakes during voting.

**Comment by Skn0tt** [comment]
As a host, I want to be able to run multiple polls in parallel.

**Comment by Skn0tt** [comment]
As a host, I want to prepare polls to be held at a later time.

**Comment by Skn0tt** [comment]
As a host, I want to run the same poll amongst different groups and compare the results.

**Comment by Skn0tt** [comment]
As a host, I want to run the same poll multiple times, so I don't need to type it out again and again.

**Comment by Skn0tt** [comment]
As a host, I want to show questions depending on answers to previous questions, so I can run complex surveys.

**Comment by Skn0tt** [comment]
As a host, I want to be able to publish new polls to the same audience without having to re-send them connection details, so I can react to changes quickly & reduce administrative overhead.

**Comment by NikkelM** [comment]
As a host as well as a participant, I want to be able to see my poll history, so I can look at results at a later time and easily compare polls from within Liquid.

**Comment by NikkelM** [comment]
> As a poll participant, I want to be able to undo my choices before I submit them, so I can reconsider or fix accidental clicks.

To extend this: In multi-question surveys, I want to be able to see a recap of all of my answers after the last question, and be able to go back to a specific question to change my answer, without having to restart the survey.

**Comment by Dassderdie** [comment]
As a poll participant I want to see my own answers in comparison to the end result. This would be especially helpful if Liquid is used  for quizzes as in TI via Zoom polls.

**Comment by PaulVII** [comment]
> As a host, I want to know that there's no way for clients to cheat, so I can actually rely on the results.
> 
> If we go with RatPack-based architecture, most of this should already be solved. For a relay-based one, this could be implemented using some kind of hash-based message authentication scheme.

Also regarding security:
As a host, I want to be able to create polls that are public (accessible by link/id/whatever we use) and private (with additional required password). Maybe even personalised passwords that can only be used once

**Comment by Skn0tt** [comment]
As a host, I want to create a poll, so I can do polls.

**Comment by Skn0tt** [comment]
As a host, I want to share a poll to clients, so I can do polls.

**Comment by Skn0tt** [comment]
As a participant, I want to take part in polls, so I can take part in them.

**Comment by PaulVII** [comment]
As a host, I want to close polls and prevent new participants to vote to have a final poll result.

**Comment by PaulVII** [comment]
I think we are done here? If someone disagrees, please reopen^^
