### ISSUE TITLE
Implement data export to file

### ISSUE THREAD

**Issue by bweengener** [hpi-swa-teaching/Liquid#210]
User Story:
As a host I want to export the raw results to a file format to analyze it.
Acceptance Criteria:
The export functionality supports the option to select a desired file format (e.g. CSV) and a destination where the file is saved. Furthermore the exported file should contain all relevant data without loss of information. 
General:

**Comment by vogelingmar** [comment]
Acceptance Criteria: We can export the poll data to a portable .csv file that can be used outside of squeak.

**Comment by matveysiva** [comment]
- [ ] csv file export

**Comment by florian-str** [comment]
The name of the button `Show results` is misleading. It should probably be renamed to `Export results`.

**Comment by matveysiva** [comment]
show results button into export csv
