### ISSUE TITLE
On CI: run SWALint

### ISSUE THREAD

**Issue by PaulVII** [hpi-swa-teaching/Liquid#3]
- Find other SWT implementations
- Current idea: make a test that just runs SWALint on everything

**Comment by Dassderdie** [comment]
* Maybe copy [the workflows from the TelegramClient](https://github.com/hpi-swa-teaching/TelegramClient/blob/master/.github/workflows/ci-linter.yml) ?

**Comment by Dassderdie** [comment]
I did a bit of research/reverse engineering:
1. [SWALint doesn't seem to have an official SmalltalkCI integration](https://github.com/hpi-swa-teaching/SwaLint/issues/13)
2. The [TelegramClient](https://github.com/hpi-swa-teaching/TelegramClient) and [MarkdownEditor](https://github.com/hpi-swa-teaching/MarkdownEditor) have Linters in their cli
They seem to work as follows:
a) You have a ci-linter workflow for github [like this](https://github.com/hpi-swa-teaching/TelegramClient/blob/master/.github/workflows/ci-linter.yml) that references `.smalltalk.lint.ston`

b) 
The [.smalltalk.lint.ston](https://github.com/hpi-swa-teaching/TelegramClient/blob/master/.smalltalk.lint.ston) specifies under `#testing` the class where all the linter rules seem to be located ([Reference for the #testing](https://github.com/hpi-swa/smalltalkCI#testcase-selection)).
Note that [.smalltalk.ston](https://github.com/hpi-swa-teaching/TelegramClient/blob/master/.smalltalk.ston) excludes this class.
c) 

> TCTLinterTests is the PR validation mechanism used to enforce linter compliance before merge. Individual rules are added as tests and required to have zero offenses.


It seems like the ci calls a function in the super class `TestCase` which then calls the in `TCTLinterTests ` specified custom made lint-functions? ...

**Comment by PaulVII** [comment]
I also looked at it a bit, and found this:
1. Yes [https://github.com/hpi-swa-teaching/SwaLint/wiki/Plans-for-the-future-~-What-YOU-can-do!](https://github.com/hpi-swa-teaching/SwaLint/wiki/Plans-for-the-future-~-What-YOU-can-do!)
2. Both Markdown and Telegram seem to just call SWALint within their linting test class. Telegram is a bit more sophisticated and tries to improve performance, while Markdown is simpler. 
 The relevant classes are here [Telegram](https://github.com/hpi-swa-teaching/TelegramClient/tree/master/packages/TelegramClient-Tests.package/TCTLinterTests.class/instance) and here [Markdown Editor](https://github.com/hpi-swa-teaching/MarkdownEditor/tree/master/packages/MarkdownEditor-Tests.package/MarkdownEditorLintTest.class/instance)
All methods with the prefix test are the actual tests and trivial, only the few other methods are needed to setup the test structure.

Telegram also defines a custom test environment for performance reasons, which is [here](https://github.com/hpi-swa-teaching/TelegramClient/tree/master/packages/TelegramClient-Tests.package/TCTScopedEnvironment.class)

**Comment by Skn0tt** [comment]
> Telegram is a bit more sophisticated and tries to improve performance, while Markdown is simpler.

Simple sounds enough for now. Let's get sophisticated once we have a proven need :D
