### ISSUE TITLE
Setting up a GitHub Team @Liquid

### ISSUE THREAD

**Issue by Skn0tt** [hpi-swa-teaching/Liquid#4]
Some GitHub Organisations allow setting up teams of individual contributors, which then can be used to give joint permissions or (especially interesting for us) mention the whole team with a single tag.

That'd be a great way for us to get 👀 from the whole team on smth, e.g. for a question where we want input from everybody.

**Comment by Skn0tt** [comment]
@codeZeilen does the @hpi-swa-teaching org have support for that?

**Comment by codeZeilen** [comment]
You mean like this? @hpi-swa-teaching/2021-student-team-13

**Comment by Skn0tt** [comment]
Exactly! Thank you :)
