### ISSUE TITLE
[Weekly] 2021-06-16

### ISSUE THREAD

**Issue by PaulVII** [hpi-swa-teaching/Liquid#83]
- [x] Zuteilung der Stories

**Comment by NikkelM** [comment]
- [ ] Unterschiede zwischen Single- und MultipleChoiceQuestions?

**Comment by Skn0tt** [comment]
- [ ] Retro

**Comment by Skn0tt** [comment]
- [ ] Stand Vortrag

**Comment by Dassderdie** [comment]
* [ ] "Übrigens: Pretty print nur manuell stimmt nicht, siehe zum Beispiel das aktuelle poppy print Projekt, das implementiert hat, dass der pretty printer nach jedem Save läuft."

**Comment by Skn0tt** [comment]
Deadline Vortrag: Freitag Abend
