### ISSUE TITLE
As a user, I want more feedback to my actions from the UI

### ISSUE THREAD

**Issue by PaulVII** [hpi-swa-teaching/Liquid#85]
Feedback from Tutor: Currently, I don't really if my actions do anything (e.g. if a poll has actually been started after pressing "Start Poll")

**Comment by Dassderdie** [comment]
* [ ] Error message visualisation

**Comment by Dassderdie** [comment]
* [ ] Close Participant Window after vote
* [ ] Close Host window after poll creation?
